<?php

namespace AppBundle\Repository;

/**
 * CompareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompareRepository extends \Doctrine\ORM\EntityRepository
{
}
