<?php

namespace AppBundle\Repository;

/**
 * ModelNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelNameRepository extends \Doctrine\ORM\EntityRepository
{
}
