<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function findArray($array)
	{
		$qb=$this->createQueryBuilder("u")
				->Select('u')
				->Where('u.id IN (:array)')
				->setParameter('array',$array);
			return $qb->getQuery()->getResult();
	}
	
	public function findSlider()
	{
		return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM
                AppBundle:Product p 
                ORDER BY p.price DESC
                '
            )
            ->setMaxResults(3)->getResult();
	}
}
